export class SignupData {
    email: String = null;
    password: String = null;
    passwordConfirm: String = null;
    name: String = null;
    surname: String = null;
    gender: String = null;
    birthDate: Date = null;
    biography: String = null;
    photoData: String = null;
    photoContentType: String = null; 
    nationality: String = null;
    isPatient: Boolean = null;
    patientName: String = null;
    patientSurname: String = null;
    patientGender: String = null;
    patientBirthDate: Date = null;
    patientNationality: String = null;
}
